version: "3.8"
services:
  api_service:
    image: "docker-app-01"
    build: .
#    restart: always
    ports:
      - 8090:8090
    networks:
      - springapimysql-net
    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/product-db?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USER: root
        SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0.33"
#    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root

networks:
  springapimysql-net: